export const GET_STUDENT_REQUEST = "GET_STUDENT_REQUEST"
export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS"
export const GET_STUDENT_FAIL = "GET_STUDENT_FAIL"

// export const GET_SINGLE_REQUEST = "GET_SINGLE_REQUEST"
// export const GET_SINGLE_SUCCESS = "GET_SINGLE_SUCCESS"
// export const GET_SINGLE_FAIL = "GET_SINGLE_FAIL"

export const CREATE_STUDENT_REQUEST = "CREATE_STUDENT_REQUEST"
export const CREATE_STUDENT_SUCCESS = "CREATE_STUDENT_SUCCESS"
export const CREATE_STUDENT_FAIL = "CREATE_STUDENT_FAIL"
export const CREATE_STUDENT_RESET = "CREATE_STUDENT_RESET"

export const UPDATE_STUDENT_REQUEST = "UPDATE_STUDENT_REQUEST"
export const UPDATE_STUDENT_SUCCESS = "UPDATE_STUDENT_SUCCESS"
export const UPDATE_STUDENT_FAIL = "UPDATE_STUDENT_FAIL"
export const UPDATE_STUDENT_RESET = "UPDATE_STUDENT_RESET"

export const DELETE_STUDENT_REQUEST = "DELETE_STUDENT_REQUEST"
export const DELETE_STUDENT_SUCCESS = "DELETE_STUDENT_SUCCESS"
export const DELETE_STUDENT_FAIL = "DELETE_STUDENT_FAIL"
export const DELETE_STUDENT_RESET = "DELETE_STUDENT_RESET"

export const SINGLE_STUDENT_REQUEST = "SINGLE_STUDENT_REQUEST"
export const SINGLE_STUDENT_SUCCESS = "SINGLE_STUDENT_SUCCESS"
export const SINGLE_STUDENT_FAIL = "SINGLE_STUDENT_FAIL"

export const CLEAR_ERROR = "CLEAR_ERROR"
